# Generated by Django 4.2.20 on 2025-05-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_author'),
        ('blog', '0011_reapply_0007_changes'),
    ]

    operations = [
    ]
